"""empty message

Revision ID: 28931c82b16c
Revises: d3ce1b5dbd72
Create Date: 2024-02-02 12:27:35.288641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28931c82b16c'
down_revision = 'd3ce1b5dbd72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=345), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
